apiVersion: v1
kind: PersistentVolume
metadata:
  name: keycloak-db-volume
  labels:
    type: local
spec:
  storageClassName: keycloak-db
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/tingmon/local-pv/keycloak-db"
