apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: ohif
  name: ohif
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ohif
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: ohif
    spec:
      containers:
        - image: orthancteam/ohif-v3:23.9.0
          name: ohif
          resources: {}
      restartPolicy: Always
status: {}
