apiVersion: v1
kind: PersistentVolume
metadata:
  name: orthanc-storage-volume
  labels:
    type: local
spec:
  storageClassName: orthanc-storage
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/tingmon/local-pv/orthanc-storage"
