apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: orthanc
  name: orthanc
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: orthanc
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: orthanc
    spec:
      containers:
        - env:
            - name: DICOM_WEB_PLUGIN_ENABLED
              value: "true"
            - name: ORTHANC_JSON
              value: |
                {
                  "Name": "Orthanc",
                  "OrthancExplorer2": {
                    "IsDefaultUI": true,
                    "UiOptions": {
                      "EnableShares": true,
                      "DefaultShareDuration": 0,
                      "ShareDurations": [0, 7, 15, 30, 90, 365],
                      "EnableOpenInOhifViewer3": true,
                      "OhifViewer3PublicRoot": "http://localhost/ohif/"
                    },
                    "Tokens" : {
                      "InstantLinksValidity": 3600,
                      "ShareType": "ohif-viewer-publication"
                    },
                    "Keycloak" : {
                      "Enable": true,
                      "Url": "http://localhost/keycloak/",
                      "Realm": "orthanc",
                      "ClientId": "orthanc"
                    }
                  },
                  "AuthenticationEnabled": false,     // because it is handled by the authorization plugin
                  "Authorization": {
                    "WebServiceRootUrl": "http://orthanc-auth-service:8000/",
                    "WebServiceUsername": "share-user",
                    "WebServicePassword": "change-me",
                    "StandardConfigurations" : [
                      "osimis-web-viewer",
                      "stone-webviewer",
                      "orthanc-explorer-2"
                    ],
                    "CheckedLevel": "studies"
                  },
                  "DicomWeb": {
                    "Enable": true,
                    "PublicRoot": "/orthanc/dicom-web/"
                  }
                }
            - name: ORTHANC__POSTGRESQL__HOST
              value: orthanc-db
            - name: STONE_WEB_VIEWER_PLUGIN_ENABLED
              value: "true"
            - name: VERBOSE_ENABLED
              value: "true"
            - name: VERBOSE_STARTUP
              value: "true"
          image: osimis/orthanc:23.9.0
          name: orthanc
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/orthanc/db
              name: orthanc-storage
      restartPolicy: Always
      volumes:
        - name: orthanc-storage
          persistentVolumeClaim:
            claimName: orthanc-storage
status: {}
