apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: orthanc-auth-service-claim0
  name: orthanc-auth-service-claim0
spec:
  storageClassName: orthanc-auth-service
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
