apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: orthanc-auth-service
  name: orthanc-auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: orthanc-auth-service
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: orthanc-auth-service
    spec:
      containers:
        - env:
            - name: ENABLE_KEYCLOAK
              value: "true"
            - name: PUBLIC_LANDING_ROOT
              value: http://localhost/orthanc/ui/app/token-landing.html
            - name: PUBLIC_OHIF_ROOT
              value: http://localhost/ohif/
            - name: PUBLIC_ORTHANC_ROOT
              value: http://localhost/orthanc/
            - name: SECRET_KEY
              value: change-me-I-am-a-secret-key
            - name: USERS
              value: |
                {
                  "share-user": "change-me"
                }
          image: orthancteam/orthanc-auth-service:23.9.0
          name: orthanc-auth-service
          resources: {}
          volumeMounts:
            - mountPath: /orthanc_auth_service/permissions.json
              name: orthanc-auth-service-claim0
      restartPolicy: Always
      volumes:
        - name: orthanc-auth-service-claim0
          persistentVolumeClaim:
            claimName: orthanc-auth-service-claim0
status: {}
