apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: orthanc-storage
  name: orthanc-storage
spec:
  storageClassName: orthanc-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi      
status: {}
